### ISSUE TITLE
Release this project as open source

### ISSUE THREAD

**Issue by bzz** [karandesai-96/devlog#5]
This could be an awesome template project for future usage in GSoC for different organizations and students.

Releasing as open souce mostly depends on adding a license file to the project, one from OSI list https://opensource.org/licenses

**Comment by karandesai-96** [comment]
@bzz Thanks for the suggestion, I made it ad-hoc for my own usage but didn't know It would be good enough for releasing. I am in my final week of GSoC, and after it ends I'll have more time than now. I will certainly polish this up and release it :checkered_flag:

**Comment by karandesai-96** [comment]
I will add in the LICENSE file quickly for now atleast.

**Comment by bzz** [comment]
Thanks a lot! I think we can close this now, after 0484e18

Hope this project can be an inspiration for students and organizations in the future!

**Comment by karandesai-96** [comment]
That's great ! @bzz Thanks for reminding me about this anyhow, I have the task of adding some ease of set up soon after GSoC. I'll make it ready before next GSoC, haha ! :smiley:
